# Generated by Django 5.1.2 on 2024-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('Saving', 'saving'), ('Current', 'current'), ('Business', 'business'), ('Corporate', 'corporate'), ('Student', 'student'), ('Retirement', 'retirement'), ('Other', 'other')], max_length=10),
        ),
    ]
