# Generated by Django 5.1.4 on 2024-12-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userbankaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='post_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userbankaccount',
            name='account_type',
            field=models.CharField(choices=[('saving', 'Saving'), ('current', 'Current'), ('business', 'Business'), ('corporate', 'Corporate'), ('student', 'Student'), ('retirement', 'Retirement'), ('other', 'Other')], max_length=10),
        ),
    ]
